/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiMediaAnalyzeRouteImport } from './routes/api/media/analyze'
import { Route as ApiMediaFileRouteImport } from './routes/api/media/file'
import { Route as ApiMediaHistoryRouteImport } from './routes/api/media/history'
import { Route as ApiMediaStartRouteImport } from './routes/api/media/start'
import { Route as ApiMediaStatusRouteImport } from './routes/api/media/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaAnalyzeRoute = ApiMediaAnalyzeRouteImport.update({
  id: '/api/media/analyze',
  path: '/api/media/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaFileRoute = ApiMediaFileRouteImport.update({
  id: '/api/media/file',
  path: '/api/media/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaHistoryRoute = ApiMediaHistoryRouteImport.update({
  id: '/api/media/history',
  path: '/api/media/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaStartRoute = ApiMediaStartRouteImport.update({
  id: '/api/media/start',
  path: '/api/media/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaStatusRoute = ApiMediaStatusRouteImport.update({
  id: '/api/media/status',
  path: '/api/media/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/media/analyze': typeof ApiMediaAnalyzeRoute
  '/api/media/file': typeof ApiMediaFileRoute
  '/api/media/history': typeof ApiMediaHistoryRoute
  '/api/media/start': typeof ApiMediaStartRoute
  '/api/media/status': typeof ApiMediaStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/media/analyze': typeof ApiMediaAnalyzeRoute
  '/api/media/file': typeof ApiMediaFileRoute
  '/api/media/history': typeof ApiMediaHistoryRoute
  '/api/media/start': typeof ApiMediaStartRoute
  '/api/media/status': typeof ApiMediaStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/media/analyze': typeof ApiMediaAnalyzeRoute
  '/api/media/file': typeof ApiMediaFileRoute
  '/api/media/history': typeof ApiMediaHistoryRoute
  '/api/media/start': typeof ApiMediaStartRoute
  '/api/media/status': typeof ApiMediaStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/history'
    | '/settings'
    | '/api/analyze'
    | '/api/download'
    | '/api/media/analyze'
    | '/api/media/file'
    | '/api/media/history'
    | '/api/media/start'
    | '/api/media/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/history'
    | '/settings'
    | '/api/analyze'
    | '/api/download'
    | '/api/media/analyze'
    | '/api/media/file'
    | '/api/media/history'
    | '/api/media/start'
    | '/api/media/status'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/history'
    | '/settings'
    | '/api/analyze'
    | '/api/download'
    | '/api/media/analyze'
    | '/api/media/file'
    | '/api/media/history'
    | '/api/media/start'
    | '/api/media/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiMediaAnalyzeRoute: typeof ApiMediaAnalyzeRoute
  ApiMediaFileRoute: typeof ApiMediaFileRoute
  ApiMediaHistoryRoute: typeof ApiMediaHistoryRoute
  ApiMediaStartRoute: typeof ApiMediaStartRoute
  ApiMediaStatusRoute: typeof ApiMediaStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/analyze': {
      id: '/api/media/analyze'
      path: '/api/media/analyze'
      fullPath: '/api/media/analyze'
      preLoaderRoute: typeof ApiMediaAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/file': {
      id: '/api/media/file'
      path: '/api/media/file'
      fullPath: '/api/media/file'
      preLoaderRoute: typeof ApiMediaFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/history': {
      id: '/api/media/history'
      path: '/api/media/history'
      fullPath: '/api/media/history'
      preLoaderRoute: typeof ApiMediaHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/start': {
      id: '/api/media/start'
      path: '/api/media/start'
      fullPath: '/api/media/start'
      preLoaderRoute: typeof ApiMediaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/status': {
      id: '/api/media/status'
      path: '/api/media/status'
      fullPath: '/api/media/status'
      preLoaderRoute: typeof ApiMediaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiMediaAnalyzeRoute: ApiMediaAnalyzeRoute,
  ApiMediaFileRoute: ApiMediaFileRoute,
  ApiMediaHistoryRoute: ApiMediaHistoryRoute,
  ApiMediaStartRoute: ApiMediaStartRoute,
  ApiMediaStatusRoute: ApiMediaStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
